name: Verify Documentation

# Triggers the workflow on push or pull request events
on: [push, pull_request]

env:
  DOXYGEN_VERSION: Release_1_9_3
  PYTHON_DEPS_ARCHIVE_NUM: 1

jobs:
  menu_inclusion:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: check for classes in the menu example
        run: |
          cd $GITHUB_WORKSPACE/continuous_integration
          python check_component_inclusion.py

  doc_build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      # check out the ModularSensors repo
      - uses: actions/checkout@v2.4.0
        with:
          path: code_docs/ModularSensors

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Restore Python Dependencies
        uses: actions/cache@v2.1.7
        id: cache_python
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ env.PYTHON_DEPS_ARCHIVE_NUM }}

      - name: Install Pygments and other m.css Python Requirements
        if: steps.cache_python.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip3 install --upgrade --upgrade-strategy only-if-needed jinja2 Pygments beautifulsoup4

      - name: Install GraphViz (dot)
        run: sudo apt-get -y install graphviz

      - name: Restore Doxygen
        id: cache_doxygen
        uses: actions/cache@v2.1.7
        with:
          path: doxygen-src
          key: ${{ runner.os }}-doxygen-${{ env.DOXYGEN_VERSION }}

      - name: Clone and build doxygen
        if: steps.cache_doxygen.outputs.cache-hit != 'true'
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/code_docs/ModularSensors/
          chmod +x continuous_integration/build-install-doxygen.sh
          sh continuous_integration/build-install-doxygen.sh

      # check out my fork of m.css, for processing Doxygen output
      - name: Checkout m.css
        uses: actions/checkout@v2.4.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: SRGDamia1/m.css
          path: code_docs/m.css

      - name: Generate all the documentation
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/code_docs/ModularSensors/
          chmod +x continuous_integration/generate-documentation.sh
          sh continuous_integration/generate-documentation.sh
